import { useState, useCallback } from "react";
import { toast } from "sonner";

const SCALE = 2;
const FONT_SIZE = 14;
const FONT_FAMILY =
    '"Noto Sans Devanagari", "Noto Serif", system-ui, sans-serif';
const HEADER_FONT = "11px system-ui, sans-serif";
const FOOTER_FONT = "9px system-ui, sans-serif";

const A4_WIDTH_PX = 595;
const A4_HEIGHT_PX = 842;
const PADDING = 40;
const CONTENT_WIDTH = A4_WIDTH_PX - PADDING * 2;
const LINE_HEIGHT = FONT_SIZE * 1.7;

function wrapText(
    ctx: CanvasRenderingContext2D,
    text: string,
    maxWidth: number,
): string[] {
    const result: string[] = [];
    const paragraphs = text.split("\n");

    for (const paragraph of paragraphs) {
        if (paragraph.trim() === "") {
            result.push("");
            continue;
        }

        const words = paragraph.split(/\s+/);
        let currentLine = "";

        for (const word of words) {
            const testLine = currentLine ? `${currentLine} ${word}` : word;
            const width = ctx.measureText(testLine).width;

            if (width > maxWidth && currentLine) {
                result.push(currentLine);
                currentLine = word;
            } else {
                currentLine = testLine;
            }
        }

        if (currentLine) {
            result.push(currentLine);
        }
    }

    return result;
}

function renderPage(
    lines: string[],
    pageNum: number,
    totalPages: number,
    title: string,
): HTMLCanvasElement {
    const canvas = document.createElement("canvas");
    canvas.width = A4_WIDTH_PX * SCALE;
    canvas.height = A4_HEIGHT_PX * SCALE;

    const ctx = canvas.getContext("2d")!;
    ctx.scale(SCALE, SCALE);

    ctx.fillStyle = "#ffffff";
    ctx.fillRect(0, 0, A4_WIDTH_PX, A4_HEIGHT_PX);
    ctx.textBaseline = "top";

    let y = PADDING;

    // Header
    ctx.font = HEADER_FONT;
    ctx.fillStyle = "#aaaaaa";
    ctx.fillText("Generated by WriteShift", PADDING, y);
    const dateStr = new Date().toLocaleDateString();
    const dateW = ctx.measureText(dateStr).width;
    ctx.fillText(dateStr, A4_WIDTH_PX - PADDING - dateW, y);
    y += 18;

    // Header Separator line
    ctx.strokeStyle = "#e0e0e0";
    ctx.lineWidth = 1;
    ctx.beginPath();
    ctx.moveTo(PADDING, y);
    ctx.lineTo(A4_WIDTH_PX - PADDING, y);
    ctx.stroke();
    y += 14;

    // Body text
    ctx.font = `${FONT_SIZE}px ${FONT_FAMILY}`;
    ctx.fillStyle = "#1a1a1a";

    for (const line of lines) {
        ctx.fillText(line, PADDING, y);
        y += LINE_HEIGHT;
    }

    // Footer
    const pageLabel = `Page ${pageNum} of ${totalPages}`;
    const pageLabelW = ctx.measureText(pageLabel).width;

    // Footer separator line
    const footerSepY = A4_HEIGHT_PX - PADDING - 4;
    ctx.strokeStyle = "#e0e0e0";
    ctx.lineWidth = 1;
    ctx.beginPath();
    ctx.moveTo(PADDING, footerSepY);
    ctx.lineTo(A4_WIDTH_PX - PADDING, footerSepY);
    ctx.stroke();

    ctx.font = FOOTER_FONT;
    ctx.fillStyle = "#bbbbbb";

    ctx.fillText(
        pageLabel,
        A4_WIDTH_PX - PADDING - pageLabelW,
        A4_HEIGHT_PX - PADDING + 10,
    );

    const footerText = "writeshift.csfahad.me";
    const footerW = ctx.measureText(footerText).width;
    ctx.fillText(
        footerText,
        (A4_WIDTH_PX - footerW) / 2,
        A4_HEIGHT_PX - PADDING + 10,
    );

    return canvas;
}

// split lines into pages
function paginateLines(lines: string[]): string[][] {
    const pages: string[][] = [];

    const FIRST_PAGE_HEADER = 18 + 14; // header + spacing
    const OTHER_PAGE_HEADER = 18 + 14;
    const FOOTER_SPACE = 10;

    const firstPageLines = Math.floor(
        (A4_HEIGHT_PX - PADDING * 2 - FIRST_PAGE_HEADER - FOOTER_SPACE) /
            LINE_HEIGHT,
    );
    const otherPageLines = Math.floor(
        (A4_HEIGHT_PX - PADDING * 2 - OTHER_PAGE_HEADER - FOOTER_SPACE) /
            LINE_HEIGHT,
    );

    // First page
    pages.push(lines.slice(0, firstPageLines));

    // Remaining pages
    let offset = firstPageLines;
    while (offset < lines.length) {
        pages.push(lines.slice(offset, offset + otherPageLines));
        offset += otherPageLines;
    }

    return pages;
}

// Single-image JPG canvas (no pagination)
function renderJpgCanvas(text: string): HTMLCanvasElement {
    const JPG_WIDTH = 800;
    const JPG_PADDING = 48;
    const JPG_CONTENT_W = JPG_WIDTH - JPG_PADDING * 2;
    const JPG_LINE_HEIGHT = FONT_SIZE * 1.8;

    const measureCanvas = document.createElement("canvas");
    const measureCtx = measureCanvas.getContext("2d")!;
    measureCtx.font = `${FONT_SIZE}px ${FONT_FAMILY}`;
    const wrappedLines = wrapText(measureCtx, text, JPG_CONTENT_W);

    const HEADER_H = 40;
    const FOOTER_H = 50;
    const TEXT_H = wrappedLines.length * JPG_LINE_HEIGHT;
    const TOTAL_H = JPG_PADDING + HEADER_H + TEXT_H + FOOTER_H + JPG_PADDING;

    const canvas = document.createElement("canvas");
    canvas.width = JPG_WIDTH * SCALE;
    canvas.height = TOTAL_H * SCALE;
    const ctx = canvas.getContext("2d")!;
    ctx.scale(SCALE, SCALE);

    // Background
    ctx.fillStyle = "#ffffff";
    ctx.fillRect(0, 0, JPG_WIDTH, TOTAL_H);
    ctx.textBaseline = "top";
    let y = JPG_PADDING;

    // Header
    ctx.font = HEADER_FONT;
    ctx.fillStyle = "#999999";
    ctx.fillText("Generated by WriteShift", JPG_PADDING, y);
    const dateStr = new Date().toLocaleDateString();
    const dateW = ctx.measureText(dateStr).width;
    ctx.fillText(dateStr, JPG_WIDTH - JPG_PADDING - dateW, y);
    y += 20;

    ctx.strokeStyle = "#e0e0e0";
    ctx.lineWidth = 1;
    ctx.beginPath();
    ctx.moveTo(JPG_PADDING, y);
    ctx.lineTo(JPG_WIDTH - JPG_PADDING, y);
    ctx.stroke();
    y += HEADER_H - 20;

    // Body
    ctx.font = `${FONT_SIZE}px ${FONT_FAMILY}`;
    ctx.fillStyle = "#1a1a1a";
    for (const line of wrappedLines) {
        ctx.fillText(line, JPG_PADDING, y);
        y += JPG_LINE_HEIGHT;
    }

    // Footer
    y += 12;
    ctx.strokeStyle = "#e0e0e0";
    ctx.beginPath();
    ctx.moveTo(JPG_PADDING, y);
    ctx.lineTo(JPG_WIDTH - JPG_PADDING, y);
    ctx.stroke();
    y += 16;
    ctx.font = FOOTER_FONT;
    ctx.fillStyle = "#bbbbbb";
    const ftxt = "writeshift.csfahad.me";
    const fw = ctx.measureText(ftxt).width;
    ctx.fillText(ftxt, (JPG_WIDTH - fw) / 2, y);

    return canvas;
}

export function useExport() {
    const [exportingPdf, setExportingPdf] = useState(false);
    const [exportingJpg, setExportingJpg] = useState(false);

    const copyToClipboard = useCallback(async (text: string) => {
        try {
            await navigator.clipboard.writeText(text);
            toast.success("Copied to clipboard");
        } catch {
            const ta = document.createElement("textarea");
            ta.value = text;
            ta.style.position = "fixed";
            ta.style.opacity = "0";
            document.body.appendChild(ta);
            ta.select();
            document.execCommand("copy");
            document.body.removeChild(ta);
            toast.success("Copied to clipboard");
        }
    }, []);

    const exportAsPdf = useCallback(async (text: string, title?: string) => {
        setExportingPdf(true);
        try {
            const pdfTitle = title || "WriteShift Export";

            const { jsPDF } = await import("jspdf");

            // 1. Measure & wrap text using Canvas 2D (browser handles Devanagari shaping)
            const measureCanvas = document.createElement("canvas");
            const measureCtx = measureCanvas.getContext("2d")!;
            measureCtx.font = `${FONT_SIZE}px ${FONT_FAMILY}`;
            const allLines = wrapText(measureCtx, text, CONTENT_WIDTH);

            // 2. Split into page groups
            const pageGroups = paginateLines(allLines);
            const totalPages = pageGroups.length;

            // 3. Create jsPDF document
            const doc = new jsPDF({
                orientation: "portrait",
                unit: "mm",
                format: "a4",
            });
            const pdfW = doc.internal.pageSize.getWidth();
            const pdfH = doc.internal.pageSize.getHeight();

            // 4. For each page: render canvas → insert as image
            for (let i = 0; i < pageGroups.length; i++) {
                if (i > 0) doc.addPage();

                const pageCanvas = renderPage(
                    pageGroups[i]!,
                    i + 1,
                    totalPages,
                    pdfTitle,
                );

                const imgData = pageCanvas.toDataURL("image/jpeg", 0.95);

                doc.addImage(imgData, "JPEG", 0, 0, pdfW, pdfH);
            }

            // 5. Download
            doc.save(`${pdfTitle}.pdf`);
            toast.success("PDF downloaded successfully");
        } catch (err: any) {
            console.error("PDF export error:", err);
            toast.error(err.message || "Failed to export PDF");
        } finally {
            setExportingPdf(false);
        }
    }, []);

    const exportAsJpg = useCallback(async (text: string, filename?: string) => {
        setExportingJpg(true);
        try {
            const canvas = renderJpgCanvas(text);
            const link = document.createElement("a");
            link.download = `${filename || "writeshift-export"}.jpg`;
            link.href = canvas.toDataURL("image/jpeg", 0.95);
            document.body.appendChild(link);
            link.click();
            document.body.removeChild(link);
            toast.success("Image downloaded successfully");
        } catch (err: any) {
            toast.error(err.message || "Failed to export image");
        } finally {
            setExportingJpg(false);
        }
    }, []);

    return {
        copyToClipboard,
        exportAsPdf,
        exportAsJpg,
        exportingPdf,
        exportingJpg,
    };
}
