import { useState, useCallback } from "react";
import { toast } from "sonner";
import { formatExtractedText } from "@/utils/formatText";

const SCALE = 2;
const FONT_SIZE = 14;
const FONT_FAMILY =
    '"Noto Sans Devanagari", "Noto Serif", system-ui, sans-serif';
const HEADER_FONT = "11px system-ui, sans-serif";
const FOOTER_FONT = "9px system-ui, sans-serif";

const A4_WIDTH_PX = 595;
const A4_HEIGHT_PX = 842;
const PADDING = 40;
const CONTENT_WIDTH = A4_WIDTH_PX - PADDING * 2;
const LINE_HEIGHT = FONT_SIZE * 1.7;

interface WrappedLine {
    text: string;
    words: string[];
    isLastInParagraph: boolean;
}

function wrapTextJustified(
    ctx: CanvasRenderingContext2D,
    text: string,
    maxWidth: number,
): WrappedLine[] {
    const result: WrappedLine[] = [];
    const paragraphs = text.split("\n");

    for (const paragraph of paragraphs) {
        if (paragraph.trim() === "") {
            result.push({ text: "", words: [], isLastInParagraph: true });
            continue;
        }

        const words = paragraph.split(/\s+/).filter(Boolean);
        let currentWords: string[] = [];
        let currentWidth = 0;
        const spaceWidth = ctx.measureText(" ").width;

        for (const word of words) {
            const wordWidth = ctx.measureText(word).width;
            const testWidth =
                currentWords.length > 0
                    ? currentWidth + spaceWidth + wordWidth
                    : wordWidth;

            if (testWidth > maxWidth && currentWords.length > 0) {
                result.push({
                    text: currentWords.join(" "),
                    words: [...currentWords],
                    isLastInParagraph: false,
                });
                currentWords = [word];
                currentWidth = wordWidth;
            } else {
                currentWords.push(word);
                currentWidth = testWidth;
            }
        }

        if (currentWords.length > 0) {
            result.push({
                text: currentWords.join(" "),
                words: currentWords,
                isLastInParagraph: true,
            });
        }
    }

    return result;
}

function drawJustifiedLine(
    ctx: CanvasRenderingContext2D,
    line: WrappedLine,
    x: number,
    y: number,
    maxWidth: number,
) {
    if (
        line.words.length === 0 ||
        line.isLastInParagraph ||
        line.words.length === 1
    ) {
        // Left-align: empty lines, single words, and last line of paragraphs
        ctx.fillText(line.text, x, y);
        return;
    }

    // Calculate total word width
    let totalWordWidth = 0;
    for (const word of line.words) {
        totalWordWidth += ctx.measureText(word).width;
    }

    // Distribute remaining space evenly between words
    const totalSpaces = line.words.length - 1;
    const spaceWidth = (maxWidth - totalWordWidth) / totalSpaces;

    let curX = x;
    for (let i = 0; i < line.words.length; i++) {
        ctx.fillText(line.words[i]!, curX, y);
        curX += ctx.measureText(line.words[i]!).width + spaceWidth;
    }
}

function renderPage(
    lines: WrappedLine[],
    pageNum: number,
    totalPages: number,
): HTMLCanvasElement {
    const canvas = document.createElement("canvas");
    canvas.width = A4_WIDTH_PX * SCALE;
    canvas.height = A4_HEIGHT_PX * SCALE;

    const ctx = canvas.getContext("2d")!;
    ctx.scale(SCALE, SCALE);

    ctx.fillStyle = "#ffffff";
    ctx.fillRect(0, 0, A4_WIDTH_PX, A4_HEIGHT_PX);
    ctx.textBaseline = "top";

    let y = PADDING;

    // Header
    ctx.font = HEADER_FONT;
    ctx.fillStyle = "#aaaaaa";
    ctx.fillText("Generated by WriteShift", PADDING, y);
    const dateStr = new Date().toLocaleDateString();
    const dateW = ctx.measureText(dateStr).width;
    ctx.fillText(dateStr, A4_WIDTH_PX - PADDING - dateW, y);
    y += 18;

    // Header separator
    ctx.strokeStyle = "#e0e0e0";
    ctx.lineWidth = 1;
    ctx.beginPath();
    ctx.moveTo(PADDING, y);
    ctx.lineTo(A4_WIDTH_PX - PADDING, y);
    ctx.stroke();
    y += 14;

    // Body text — justified
    ctx.font = `${FONT_SIZE}px ${FONT_FAMILY}`;
    ctx.fillStyle = "#1a1a1a";

    for (const line of lines) {
        drawJustifiedLine(ctx, line, PADDING, y, CONTENT_WIDTH);
        y += LINE_HEIGHT;
    }

    // Footer separator
    const footerSepY = A4_HEIGHT_PX - PADDING - 4;
    ctx.strokeStyle = "#e0e0e0";
    ctx.lineWidth = 1;
    ctx.beginPath();
    ctx.moveTo(PADDING, footerSepY);
    ctx.lineTo(A4_WIDTH_PX - PADDING, footerSepY);
    ctx.stroke();

    // Footer text
    ctx.font = FOOTER_FONT;
    ctx.fillStyle = "#bbbbbb";
    const pageLabel = `Page ${pageNum} of ${totalPages}`;
    const pageLabelW = ctx.measureText(pageLabel).width;
    ctx.fillText(
        pageLabel,
        A4_WIDTH_PX - PADDING - pageLabelW,
        A4_HEIGHT_PX - PADDING + 10,
    );
    const footerText = "writeshift.csfahad.me";
    const footerW = ctx.measureText(footerText).width;
    ctx.fillText(
        footerText,
        (A4_WIDTH_PX - footerW) / 2,
        A4_HEIGHT_PX - PADDING + 10,
    );

    return canvas;
}

function paginateLines(lines: WrappedLine[]): WrappedLine[][] {
    const pages: WrappedLine[][] = [];
    const PAGE_HEADER = 18 + 14;
    const FOOTER_SPACE = 10;
    const linesPerPage = Math.floor(
        (A4_HEIGHT_PX - PADDING * 2 - PAGE_HEADER - FOOTER_SPACE) / LINE_HEIGHT,
    );

    let offset = 0;
    while (offset < lines.length) {
        pages.push(lines.slice(offset, offset + linesPerPage));
        offset += linesPerPage;
    }

    // always have at least one page
    if (pages.length === 0) pages.push([]);

    return pages;
}

// JPG canvas
function renderJpgCanvas(text: string): HTMLCanvasElement {
    const JPG_WIDTH = 800;
    const JPG_PADDING = 48;
    const JPG_CONTENT_W = JPG_WIDTH - JPG_PADDING * 2;
    const JPG_LINE_HEIGHT = FONT_SIZE * 1.8;

    const measureCanvas = document.createElement("canvas");
    const measureCtx = measureCanvas.getContext("2d")!;
    measureCtx.font = `${FONT_SIZE}px ${FONT_FAMILY}`;
    const wrappedLines = wrapTextJustified(measureCtx, text, JPG_CONTENT_W);

    const HEADER_H = 40;
    const FOOTER_H = 50;
    const TEXT_H = wrappedLines.length * JPG_LINE_HEIGHT;
    const TOTAL_H = JPG_PADDING + HEADER_H + TEXT_H + FOOTER_H + JPG_PADDING;

    const canvas = document.createElement("canvas");
    canvas.width = JPG_WIDTH * SCALE;
    canvas.height = TOTAL_H * SCALE;
    const ctx = canvas.getContext("2d")!;
    ctx.scale(SCALE, SCALE);

    ctx.fillStyle = "#ffffff";
    ctx.fillRect(0, 0, JPG_WIDTH, TOTAL_H);
    ctx.textBaseline = "top";
    let y = JPG_PADDING;

    // Header
    ctx.font = HEADER_FONT;
    ctx.fillStyle = "#999999";
    ctx.fillText("Generated by WriteShift", JPG_PADDING, y);
    const dateStr = new Date().toLocaleDateString();
    const dateW = ctx.measureText(dateStr).width;
    ctx.fillText(dateStr, JPG_WIDTH - JPG_PADDING - dateW, y);
    y += 20;

    ctx.strokeStyle = "#e0e0e0";
    ctx.lineWidth = 1;
    ctx.beginPath();
    ctx.moveTo(JPG_PADDING, y);
    ctx.lineTo(JPG_WIDTH - JPG_PADDING, y);
    ctx.stroke();
    y += HEADER_H - 20;

    // Body — justified
    ctx.font = `${FONT_SIZE}px ${FONT_FAMILY}`;
    ctx.fillStyle = "#1a1a1a";
    for (const line of wrappedLines) {
        drawJustifiedLine(ctx, line, JPG_PADDING, y, JPG_CONTENT_W);
        y += JPG_LINE_HEIGHT;
    }

    // Footer
    y += 12;
    ctx.strokeStyle = "#e0e0e0";
    ctx.beginPath();
    ctx.moveTo(JPG_PADDING, y);
    ctx.lineTo(JPG_WIDTH - JPG_PADDING, y);
    ctx.stroke();
    y += 16;
    ctx.font = FOOTER_FONT;
    ctx.fillStyle = "#bbbbbb";
    const ftxt = "writeshift.csfahad.me";
    const fw = ctx.measureText(ftxt).width;
    ctx.fillText(ftxt, (JPG_WIDTH - fw) / 2, y);

    return canvas;
}

export function useExport() {
    const [exportingPdf, setExportingPdf] = useState(false);
    const [exportingJpg, setExportingJpg] = useState(false);
    const [exportingDocx, setExportingDocx] = useState(false);

    const copyToClipboard = useCallback(async (text: string) => {
        try {
            await navigator.clipboard.writeText(text);
            toast.success("Copied to clipboard");
        } catch {
            const ta = document.createElement("textarea");
            ta.value = text;
            ta.style.position = "fixed";
            ta.style.opacity = "0";
            document.body.appendChild(ta);
            ta.select();
            document.execCommand("copy");
            document.body.removeChild(ta);
            toast.success("Copied to clipboard");
        }
    }, []);

    const exportAsPdf = useCallback(async (text: string, title?: string) => {
        setExportingPdf(true);
        try {
            const formatted = formatExtractedText(text);
            const pdfTitle = title || "WriteShift Export";
            const { jsPDF } = await import("jspdf");

            const measureCanvas = document.createElement("canvas");
            const measureCtx = measureCanvas.getContext("2d")!;
            measureCtx.font = `${FONT_SIZE}px ${FONT_FAMILY}`;
            const allLines = wrapTextJustified(
                measureCtx,
                formatted,
                CONTENT_WIDTH,
            );

            const pageGroups = paginateLines(allLines);
            const totalPages = pageGroups.length;

            const doc = new jsPDF({
                orientation: "portrait",
                unit: "mm",
                format: "a4",
            });
            const pdfW = doc.internal.pageSize.getWidth();
            const pdfH = doc.internal.pageSize.getHeight();

            for (let i = 0; i < pageGroups.length; i++) {
                if (i > 0) doc.addPage();
                const pageCanvas = renderPage(
                    pageGroups[i]!,
                    i + 1,
                    totalPages,
                );
                const imgData = pageCanvas.toDataURL("image/jpeg", 0.95);
                doc.addImage(imgData, "JPEG", 0, 0, pdfW, pdfH);
            }

            doc.save(`${pdfTitle}.pdf`);
            toast.success("PDF downloaded successfully");
        } catch (err: any) {
            console.error("PDF export error:", err);
            toast.error(err.message || "Failed to export PDF");
        } finally {
            setExportingPdf(false);
        }
    }, []);

    const exportAsJpg = useCallback(async (text: string, filename?: string) => {
        setExportingJpg(true);
        try {
            const formatted = formatExtractedText(text);
            const canvas = renderJpgCanvas(formatted);
            const link = document.createElement("a");
            link.download = `${filename || "writeshift-export"}.jpg`;
            link.href = canvas.toDataURL("image/jpeg", 0.95);
            document.body.appendChild(link);
            link.click();
            document.body.removeChild(link);
            toast.success("Image downloaded successfully");
        } catch (err: any) {
            toast.error(err.message || "Failed to export image");
        } finally {
            setExportingJpg(false);
        }
    }, []);

    const exportAsDocx = useCallback(async (text: string, title?: string) => {
        setExportingDocx(true);
        try {
            const formatted = formatExtractedText(text);
            const docxTitle = title || "WriteShift Export";

            const {
                Document,
                Paragraph,
                TextRun,
                Header,
                Footer,
                AlignmentType,
                Packer,
                PageNumber,
                NumberFormat,
            } = await import("docx");
            const { saveAs } = await import("file-saver");

            const paragraphs = formatted.split("\n");
            const docParagraphs = paragraphs.map(
                (p) =>
                    new Paragraph({
                        alignment: AlignmentType.JUSTIFIED,
                        spacing: {
                            after: p.trim() === "" ? 200 : 120,
                            line: 360,
                        },
                        children: [
                            new TextRun({
                                text: p,
                                font: "Noto Sans Devanagari",
                                size: 24, // 12pt in half-points
                            }),
                        ],
                    }),
            );

            const doc = new Document({
                creator: "WriteShift",
                description: "Generated by WriteShift — Handwriting to Text",
                sections: [
                    {
                        properties: {
                            page: {
                                margin: {
                                    top: 1440, // 1 inch = 1440 twips
                                    bottom: 1440,
                                    left: 1440,
                                    right: 1440,
                                },
                                pageNumbers: {
                                    start: 1,
                                    formatType: NumberFormat.DECIMAL,
                                },
                            },
                        },
                        headers: {
                            default: new Header({
                                children: [
                                    new Paragraph({
                                        alignment: AlignmentType.CENTER,
                                        children: [
                                            new TextRun({
                                                text: "Generated by WriteShift",
                                                font: "Arial",
                                                size: 16, // 8pt
                                                color: "999999",
                                            }),
                                        ],
                                    }),
                                ],
                            }),
                        },
                        footers: {
                            default: new Footer({
                                children: [
                                    new Paragraph({
                                        alignment: AlignmentType.CENTER,
                                        children: [
                                            new TextRun({
                                                text: "writeshift.csfahad.me · Page ",
                                                font: "Arial",
                                                size: 14, // 7pt
                                                color: "BBBBBB",
                                            }),
                                            new TextRun({
                                                children: [PageNumber.CURRENT],
                                                font: "Arial",
                                                size: 14,
                                                color: "BBBBBB",
                                            }),
                                        ],
                                    }),
                                ],
                            }),
                        },
                        children: [...docParagraphs],
                    },
                ],
            });

            const blob = await Packer.toBlob(doc);
            saveAs(blob, `${docxTitle}.docx`);
            toast.success("DOCX downloaded successfully");
        } catch (err: any) {
            console.error("DOCX export error:", err);
            toast.error(err.message || "Failed to export DOCX");
        } finally {
            setExportingDocx(false);
        }
    }, []);

    return {
        copyToClipboard,
        exportAsPdf,
        exportAsJpg,
        exportAsDocx,
        exportingPdf,
        exportingJpg,
        exportingDocx,
    };
}
