import { jsPDF } from "jspdf";
import { readFileSync, existsSync, statSync } from "fs";
import { join } from "path";

let devanagariFont: string | null = null;
let fontInitialized = false;

function initializeFont() {
    if (fontInitialized) return;
    fontInitialized = true;

    const fontsDir = join(import.meta.dir, "../../assets/fonts");

    const candidates = [
        "NotoSansDevanagari-Regular.ttf",
        "NotoSansDevanagari[wdth,wght].ttf",
        "NotoSansDevanagari-VariableFont_wdth,wght.ttf",
    ];

    let fontPath: string | null = null;
    for (const name of candidates) {
        const path = join(fontsDir, name);
        if (existsSync(path)) {
            fontPath = path;
            break;
        }
    }

    if (!fontPath) {
        console.warn("No Noto Sans Devanagari font found in:", fontsDir);
        console.warn("Hindi text in PDFs will render as garbled text.");
        console.warn("To fix: download the STATIC (non-variable) font from: ");
        console.warn(
            "https://fonts.google.com/noto/specimen/Noto+Sans+Devanagari",
        );
        console.warn(
            "Extract NotoSansDevanagari-Regular.ttf from the static/ folder ",
        );
        console.warn("and place it in:", fontsDir);
        return;
    }

    const fileSize = statSync(fontPath).size;
    console.log(
        `Loading font: ${fontPath} (${(fileSize / 1024).toFixed(0)} KB)`,
    );

    try {
        const fontBuffer = readFileSync(fontPath);
        devanagariFont = fontBuffer.toString("base64");
        console.log("Noto Sans Devanagari registered with jsPDF");
    } catch (err) {
        console.error("Failed to read font file:", err);
    }
}

function containsDevanagari(text: string): boolean {
    return /[\u0900-\u097F]/.test(text);
}

interface PdfOptions {
    fontSize?: number;
    title?: string;
}

export async function generatePdf(
    text: string,
    options: PdfOptions = {},
): Promise<ArrayBuffer> {
    initializeFont();

    const { fontSize = 14, title = "WriteShift Export" } = options;
    const doc = new jsPDF({
        orientation: "portrait",
        unit: "mm",
        format: "a4",
    });

    if (devanagariFont) {
        doc.addFileToVFS("NotoSansDevanagari-Regular.ttf", devanagariFont);
        doc.addFont(
            "NotoSansDevanagari-Regular.ttf",
            "NotoSansDevanagari",
            "normal",
        );
    }

    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    const margin = 20;
    const contentWidth = pageWidth - margin * 2;
    const lineHeight = fontSize * 0.5;
    let y = margin + 10;

    function setDevanagariFont() {
        if (devanagariFont) {
            doc.setFont("NotoSansDevanagari", "normal");
        } else {
            doc.setFont("helvetica", "normal");
        }
    }

    // --- Header ---
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.setFont("helvetica", "normal");
    doc.text("Generated by WriteShift", margin, margin - 5);
    doc.text(new Date().toLocaleDateString(), pageWidth - margin, margin - 5, {
        align: "right",
    });

    // --- Separator ---
    doc.setDrawColor(200);
    doc.line(margin, y, pageWidth - margin, y);
    y += 8;

    // --- Body text ---
    doc.setFontSize(fontSize);
    doc.setTextColor(50);

    const hasDevanagari = containsDevanagari(text);
    if (hasDevanagari) {
        setDevanagariFont();
    } else {
        doc.setFont("helvetica", "normal");
    }

    const lines = doc.splitTextToSize(text, contentWidth) as string[];

    for (let i = 0; i < lines.length; i++) {
        const line = lines[i]!;

        if (y + lineHeight > pageHeight - margin) {
            doc.addPage();
            y = margin;

            // New page header
            doc.setFontSize(8);
            doc.setTextColor(150);
            doc.setFont("helvetica", "normal");
            doc.text("Generated by WriteShift", margin, margin - 5);
            doc.text(
                `Page ${doc.getNumberOfPages()}`,
                pageWidth - margin,
                margin - 5,
                { align: "right" },
            );

            // Restore body font
            doc.setFontSize(fontSize);
            doc.setTextColor(50);
            if (hasDevanagari) {
                setDevanagariFont();
            } else {
                doc.setFont("helvetica", "normal");
            }
        }

        doc.text(line, margin, y);
        y += lineHeight;
    }

    // --- Footer ---
    doc.setFontSize(7);
    doc.setTextColor(180);
    doc.setFont("helvetica", "normal");
    doc.text("writeshift.csfahad.me", pageWidth / 2, pageHeight - 10, {
        align: "center",
    });

    return doc.output("arraybuffer");
}
